# Generated by Django 5.0.14 on 2025-10-10 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_appointment_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('done', 'Done')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='hospital.patient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
