# Generated by Django 5.0.14 on 2025-10-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_queuetoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuetoken',
            options={'ordering': ['created_at'], 'verbose_name': 'Queue Token', 'verbose_name_plural': 'Queue Tokens'},
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='token_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='queuetoken',
            unique_together={('token_number', 'department')},
        ),
    ]
