# Generated by Django 5.0.14 on 2025-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_queuetoken_options_queuetoken_called_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuetoken',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='queuetoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('done', 'Done')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='token_number',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='queuetoken',
            name='called_at',
        ),
        migrations.RemoveField(
            model_name='queuetoken',
            name='completed_at',
        ),
    ]
