# Generated by Django 5.0.14 on 2025-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_queuetoken_enhancement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='queuetoken',
            new_name='hospital_qu_status_02f5e9_idx',
            old_name='hospital_qu_status_7f2b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='queuetoken',
            new_name='hospital_qu_created_5a7378_idx',
            old_name='hospital_qu_created_8a1c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='queuetoken',
            new_name='hospital_qu_patient_e41093_idx',
            old_name='hospital_qu_patient_9d3e5g_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
