# Generated by Django 5.0.14 on 2025-10-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_rename_hospital_qu_status_7f2b8b_idx_hospital_qu_status_02f5e9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient'),
        ),
    ]
